pointcloud_to_laserscan_node:
  ros__parameters:
    target_frame: map
    transform_tolerance: 0.001
    min_height: 0.0
    max_height: 1.0
    angle_min: -1.5708 # -M_PI/2
    angle_max: 1.5708 # M_PI/2
    angle_increment: 0.0087 # M_PI/360.0
    scan_time: 0.333
    range_min: 0.45
    range_max: 10.0
    use_inf: true
    inf_epsilon: 1.0