pointcloud_filter_node:
  ros__parameters:
    
    # Topics
    input_pointcloud_topic_name: "/point_cloud/raw"
    input_pointcloud_topic_queue_size: 10
    input_pointcloud_topic_frame_id: "radar"

    output_pointcloud_topic_name: "/point_cloud/filtered"
    output_pointcloud_topic_queue_size: 10
    output_pointcloud_topic_frame_id: "map"

    # Parameters
    crop_box:
      x_min: 0.8
      x_max: -0.1
      y_min: -0.25
      y_max: 0.25
      z_min: -0.25
      z_max: 0.25

    # Visualization
    visualize_debug: True
    visualization_timer_period: 0.1 # in seconds

    crop_box_visualization_topic_name: "/pointcloud_filter/crop_box_visualization"
    crop_box_visualization_topic_queue_size: 10