go2_camera_node:
  ros__parameters:

    image_pub_topic_name: "camera/raw"
    image_pub_topic_queue_size: 10
    image_pub_topic_frame_id: "camera_link"
    image_pub_topic_rate: 30.0

    camera_address: # In string
      address: "230.1.1.1"
      port: "1720"
      multicast-iface: "wlp2s0"
