scan_procedure_node:
  ros__parameters:
    
    # ROS2 Scanning Procedure Parameters
    # The following parameters are used to configure the ROS2 Scanning Procedure.

    pointcloud_topic_name: "point_cloud/buffer"
    pointcloud_queue_size: 1

    trigger_subscriber_topic_name: "perform_scan"
    trigger_subscriber_queue_size: 1

    gesture_publisher_topic_name: "gesture"
    gesture_publisher_queue_size: 1

    navigate_to_pose_service_name: "send_robot"

    get_image_service_name: "get_image"

    scan_number_of_orientations: 8            # Number of orientations to scan at each waypoint
    scan_delay_between_orientations: 1.0      # Delay between each orientation in seconds
    scan_pointcloud_buffer_time: 2.0         # Time to buffer pointclouds in seconds
    scan_gesture_sequence:                    # Sequence of gestures to perform during scan
    - "stand_up"
    - "sit"
    - "recover"
    scan_gesture_delay: 1.0                   # Delay after a gesture in seconds