pointcloud_transformer_node:
  ros__parameters:

    # Topics
    input_pointcloud_topic_name: "point_cloud/camera/raw"
    output_pointcloud_topic_name: "point_cloud/camera/transformed"

    # Parameters
    source_frame_id: "d435i_camera_depth_optical_frame"
    target_frame_id: "radar"