hardware_interface_node:
  ros__parameters:
    input:
      # Input topics from unitree_ros2
      low_level_state_topic: "/lowstate"
      low_level_state_queue_size: 10

      high_level_state_topic: "/sportmodestate"
      high_level_state_queue_size: 10

      lidar_point_cloud_topic: "/utlidar/cloud"
      lidar_point_cloud_queue_size: 10
      lidar_point_cloud_frame: "utlidar"

      camera_image_topic: "/image"
      camera_image_queue_size: 10

    output:
      # Output topics to ltm_stacks
      joint_state_topic: "/joint_states"
      joint_state_queue_size: 10

      lidar_point_cloud_topic: "/point_cloud/raw"
      lidar_point_cloud_queue_size: 10
      lidar_point_cloud_frame: "radar"

      180p_image_topic: "/front_camera/180p"
      180p_image_queue_size: 10

      360p_image_topic: "/front_camera/360p"
      360p_image_queue_size: 10

      720p_image_topic: "/front_camera/720p"
      720p_image_queue_size: 10
    
