pointcloud_buffer_node:
  ros__parameters:
    buffer_time: 0.5 # time unit in seconds
    source_frame: "radar"
    target_frame: "odom"
    topics:
      raw_pointcloud_topic: "/point_cloud/raw"
      buffered_pointcloud_topic: "/point_cloud/buffer"