uint8 state

# Mission states
uint8 STATE_UNDEFINED   = 0
uint8 STATE_BOOTUP      = 1
uint8 STATE_LOAD_MAP    = 2
uint8 STATE_CREATE_MAP  = 3
uint8 STATE_LOCALIZE    = 4
uint8 STATE_STANDBY     = 5
uint8 STATE_PLANNING    = 6
uint8 STATE_NAVIGATE    = 7
uint8 STATE_MANUAL      = 8
uint8 STATE_SCAN        = 9
uint8 STATE_RETURN      = 10
uint8 STATE_SHUTDOWN    = 11
uint8 STATE_ERROR       = 12
uint8 STATE_EMERGENCY   = 13