pointcloud_mux_node:
  ros__parameters:

    input_1_pointcloud_topic_name: "point_cloud/raw"
    input_1_lidar_pointcloud_topic_queue_size: 10

    input_2_pointcloud_topic_name: "point_cloud/camera/transformed"
    input_2_pointcloud_topic_queue_size: 10

    output_mux_pointcloud_topic_name: "point_cloud/mux"
    output_mux_pointcloud_topic_queue_size: 10
    output_mux_pointcloud_topic_period: 0.5 # [s]
    output_mux_pointcloud_topic_frame_id: "radar"  # TODO